name: porfore
description: "Personal portfolio website built with Flutter Web."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.13.3

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  intl: ^0.20.3
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/edgelayer.png
  fonts:
    - family: Handlee
      fonts:
        - asset: assets/fonts/Handlee-Regular.ttf
    - family: Kalam
      fonts:
        - asset: assets/fonts/Kalam-Light.ttf
    - family: KimjungchulScript
      fonts:
        - asset: assets/fonts/KimjungchulScript-Regular.ttf
    - family: KleeOne
      fonts:
        - asset: assets/fonts/KleeOne-Regular.ttf
    - family: ShinDongYupHandwriting
      fonts:
        - asset: assets/fonts/ShinDongYupHandwriting-R.ttf
    - family: YujiSyuku
      fonts:
        - asset: assets/fonts/YujiSyuku-Regular.ttf
